version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
